// activities/tpsi5/vue_debug_d/starter/src/App.vue
<script setup>
import { reactive, ref } from "vue";
import PostCard from "./components/PostCard.vue";

const state = reactive({ title: "Feed debug" });
const { title } = state;
const posts = ref([
  { id:"p1", author:"Ada", text:"Primo", likes:0, liked:false },
  { id:"p2", author:"Linus", text:"Secondo", likes:1, liked:true },
]);
const postCount = ref(posts.value.length);

function addPost(){posts.value=[{id:crypto.randomUUID(),author:"Student",text:"Nuovo",likes:0,liked:false},...posts.value];}
function toggleLike(id){const p=posts.value.find(x=>x.id===id);if(p)p.liked=!p.liked;}
</script>
<template><main><h1>{{ title }}</h1><p>Post: {{ postCount }}</p><button @click="addPost">Aggiungi</button><PostCard v-for="(post,index) in posts" :key="index" :post="post" @toggle-like="toggleLike"/></main></template>

// activities/tpsi5/react_post_card_b/starter/src/App.jsx
import { useState } from "react";
import { PostCard } from "./components/PostCard.jsx";

const initialPosts = [
  { id: "p1", text: "Primo post", liked: false, likes: 0, author: "Alice" },
  { id: "p2", text: "Secondo post", liked: true, likes: 3, author: "Bob" },
];

export default function App() {
  const [posts, setPosts] = useState(initialPosts);
  const currentUser = "Alice";

  function toggleLike(id) {
    setPosts((current) =>
      current.map((post) =>
        post.id === id
          ? {
              ...post,
              liked: !post.liked,
              likes: post.liked ? post.likes - 1 : post.likes + 1,
            }
          : post,
      ),
    );
  }

  function deletePost(id) {
    setPosts((current) => current.filter((post) => post.id !== id));
  }

  return (
    <main>
      <h1>React PostCard translation</h1>
      {posts.map((post) => (
        <PostCard
          key={post.id}
          post={post}
          canDelete={post.author === currentUser}
          onToggleLike={toggleLike}
          onDelete={deletePost}
        />
      ))}
    </main>
  );
}
